name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop, release/* ]
  pull_request:
    branches: [ develop, release/* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/CreativeMinds.Integrations.HeySender.sln'
      PROJECT: 'src/CreativeMinds.Integrations.HeySender/CreativeMinds.Integrations.HeySender.csproj'
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Add NuGet package source
        run: dotnet nuget add source https://nuget.pkg.github.com/CreativeMindsDK/index.json -n github -u steentottrup -p ${{secrets.NUGET_API_KEY}} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore $SOLUTION

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.x

      - name: Set version
        run: |
         echo "Buid version is ${{github.run_number}}"
         sed -i "s/\(<Version>\([0-9]\+\.\)\{2\}\)\([0-9]\+\)/\1${{github.run_number}}/" ${{env.PROJECT}}       

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

#      - name: Run tests
#        run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: Pack
        working-directory: ./src/CreativeMinds.Integrations.HeySender
        run: dotnet pack --configuration $BUILD_CONFIG

      - name: Publish
        working-directory: ./src/CreativeMinds.Integrations.HeySender
        run: nuget push **\*.nupkg -Source 'https://nuget.pkg.github.com/CreativeMindsDK/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
